name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix: # Support latest and one minor back
        go: ["1.22", "1.23"]
    env:
      GOFLAGS: -mod=readonly

    services:
      etcd:
        image: gcr.io/etcd-development/etcd:v3.5.16
        ports:
          - 2379
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
        options: --health-cmd "ETCDCTL_API=3 etcdctl --endpoints http://localhost:2379 endpoint health" --health-interval 10s --health-timeout 5s --health-retries 5

      consul:
        image: hashicorp/consul:1.19
        ports:
          - 8500

      zk:
        image: zookeeper:3.8
        ports:
          - 2181

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          stable: "false"
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        env:
          ETCD_ADDR: http://localhost:${{ job.services.etcd.ports[2379] }}
          CONSUL_ADDR: localhost:${{ job.services.consul.ports[8500] }}
          ZK_ADDR: localhost:${{ job.services.zk.ports[2181] }}
        run: go test -v -race -coverprofile=coverage.coverprofile -covermode=atomic -tags integration ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.coverprofile
